// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
//
// SPDX-License-Identifier: MIT

package core

import (
	"bufio"
	"bytes"
	"fmt"
	"strings"
)

// Marker is the single-line sentinel pf-cli writes at the top of every
// generated file whose policy is "overwrite in place" (Policy.Marker: true).
// Detecting this line is how the dispatcher decides a file is safe to
// overwrite without --force.
//
// '#' is the comment leader in every ignore-file dialect we generate (git,
// docker, npm, eslint, prettier) plus YAML (FUNDING.yml).
const Marker = "# pf-cli-managed: yes"

// MarkerHTML is the equivalent sentinel used inside Markdown documents
// (SECURITY.md, CODE_OF_CONDUCT.md). The '#'-leader form would render as
// an H1 heading in Markdown, so renderers emit the HTML-comment form there.
const MarkerHTML = "<!-- pf-cli-managed: yes -->"

// YAMLDocStart is the YAML document-start marker emitted at the very top of
// every pf-cli-written YAML file. yamllint's default config (rule
// document-start: {present: true}) rejects a YAML document missing one.
// Bridges that assemble YAML by hand (FUNDING.yml, .releaserc.yaml) prepend
// this before the REUSE header to match the projectfile.yaml convention
// (--- first, then SPDX comments, then body). rawdoc.YAMLNode.Marshal already
// emits it for canvas-based writers (CITATION.cff, projectfile.yaml).
const YAMLDocStart = "---\n"

// markerScanLines bounds how far into an existing file we search for the
// marker. Real banners are 4-6 lines; scanning a fixed window keeps the
// detector cheap even on a hand-edited multi-megabyte file.
const markerScanLines = 20

// HasMarker reports whether the first markerScanLines of data contain
// Marker or MarkerHTML (after whitespace trimming).
func HasMarker(data []byte) bool {
	scanner := bufio.NewScanner(bytes.NewReader(data))
	for i := 0; i < markerScanLines && scanner.Scan(); i++ {
		line := strings.TrimSpace(scanner.Text())
		if line == Marker || line == MarkerHTML {
			return true
		}
	}
	return false
}

// Banner returns the top-of-file block including the trailing Marker line
// for ignore-file renderers. filename is the on-disk name (e.g. ".gitignore"),
// extKey is the [org.projectfile.ignores.<extKey>] sub-namespace pointer
// (e.g. "git"), and stack is the projectfile's stack list (rendered as the
// "Stack: a, b, c" line). The block ends with one blank line so generated
// content can start cleanly.
func Banner(filename, extKey string, stack []string) string {
	return BannerWithEditors(filename, extKey, stack, nil)
}

// BannerWithEditors extends Banner with an optional Editors line. When
// editors is non-empty the line is appended between Stack and the help
// text so the generated file header is self-documenting.
func BannerWithEditors(filename, extKey string, stack []string, editors []string) string {
	stackList := "(none)"
	if len(stack) > 0 {
		stackList = strings.Join(stack, ", ")
	}
	editorsLine := ""
	if len(editors) > 0 {
		editorsLine = fmt.Sprintf("# Editors: %s\n", strings.Join(editors, ", "))
	}
	return fmt.Sprintf(`# %s — generated by `+"`pf-bridge ignore`"+`
# Stack: %s
%s# Edit projectfile [org.projectfile.ignores.%s] include/exclude to
# customise — direct edits here are overwritten on the next generation.
%s

`, filename, stackList, editorsLine, extKey, Marker)
}
