// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
//
// SPDX-License-Identifier: MIT

// Command pf-bridge-fundingjson is generated by .scripts/gen-bridge-cmds.sh.
package main

import (
	_ "projectfile.org/projectfile/bridge/internal/bridge/fundingjson"

	"projectfile.org/projectfile/bridge/internal/bridgerun"
)

func main() { bridgerun.Main("pf-bridge-fundingjson") }
