// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
//
// SPDX-License-Identifier: MIT

// Command pf-bridge-cache is generated by .scripts/gen-bridge-cmds.sh.
package main

import (
	"projectfile.org/projectfile/bridge/internal/cachecmd"
)

func main() { cachecmd.Main("pf-bridge-cache") }
