// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
//
// SPDX-License-Identifier: MIT

// Command pf-bridge-release-notes is generated by .scripts/gen-bridge-cmds.sh.
package main

import (
	"projectfile.org/projectfile/bridge/internal/releasenotescmd"
)

func main() { releasenotescmd.Main("pf-bridge-release-notes") }
