// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
//
// SPDX-License-Identifier: MIT

package cff

import (
	"fmt"
	"os"

	"gopkg.in/yaml.v3"

	"kiota.ch/projectfile/core/v2/pkg/rawdoc"
)

// defaultHeaderComment is applied when a document is being written for the
// first time (Rest is nil and there is no on-disk file to inherit a header
// from). When the file already exists, the existing head comment is preserved
// by the Rest node tree.
const defaultHeaderComment = " CITATION.cff generated by projectfile/cli\n" +
	" https://citation-file-format.github.io/"

// Write serialises doc to CITATION.cff under dir.
//
//   - If doc.Rest is set (Read populated it, or Clone carried it across), the
//     typed fields are painted back onto the raw node tree — comments, key
//     order, and unknown keys all survive.
//   - If doc.Rest is nil (fresh document being created), a new mapping is
//     built from the typed view with a default header comment. There is
//     intentionally no on-disk fallback: the in-memory document must be
//     self-sufficient.
func Write(dir string, doc *Document) error {
	path := FullPath(dir)

	canvas := doc.Rest
	if canvas == nil {
		canvas = rawdoc.NewYAMLNode()
	}
	// Re-assert the banner unconditionally so a sync run stamps the pf-cli
	// pedigree even on files whose head comment was hand-edited. REUSE is
	// authoritative for the same reason; both are prepended overwriting
	// whatever was on disk, matching the discipline of every other
	// pf-cli-written artefact.
	canvas.SetHeadComment(defaultHeaderComment)

	// Prune legacy non-spec top-level keys we no longer emit. CFF 1.2.0
	// only defines `authors` and `contact` for people; older pf-cli output
	// included `maintainers` / `contributors` and any on-disk file from
	// that era still carries them. Without an explicit Delete, the painter
	// (which only writes typed keys) would leave them stranded and the
	// validator would reject the result.
	canvas.Delete("maintainers")
	canvas.Delete("contributors")

	if err := paintTypedFieldsOntoCanvas(doc, canvas); err != nil {
		return fmt.Errorf("paint CFF document onto canvas: %w", err)
	}

	data, err := canvas.Marshal()
	if err != nil {
		return fmt.Errorf("marshal CFF: %w", err)
	}
	// Runtime gate: validate against the embedded CFF 1.2.0 schema before
	// touching disk. The mapper's shape-aware copy is the producer-side fix
	// for the person/entity bug class; this is the belt-and-braces check
	// that catches drift in any future caller — and any human-edited canvas
	// that has slipped through Read. Validate on the typed YAML body
	// (REUSE header is not YAML content).
	if err := Validate(data); err != nil {
		return fmt.Errorf("CITATION.cff schema validation: %w", err)
	}
	if doc.ReuseHeader != "" {
		data = append([]byte(doc.ReuseHeader), data...)
	}
	if len(data) > 0 && data[len(data)-1] != '\n' {
		data = append(data, '\n')
	}
	return os.WriteFile(path, data, 0o644) // #nosec G306 -- metadata file, not a secret
}

// WriteMerge is the legacy name retained for callers that haven't moved to
// Write yet. It is identical behaviour.
func WriteMerge(dir string, doc *Document) error {
	return Write(dir, doc)
}

// paintTypedFieldsOntoCanvas marshals the typed doc to a yaml.Node and copies
// each top-level key into the canvas. Unknown keys on the canvas (anything
// the typed view does not understand) are left alone.
func paintTypedFieldsOntoCanvas(doc *Document, canvas *rawdoc.YAMLNode) error {
	// Marshal the typed view into an intermediate node tree to obtain stable
	// node values per key.
	tmp := &yaml.Node{}
	if err := tmp.Encode(doc); err != nil {
		return err
	}
	if tmp.Kind == yaml.DocumentNode {
		if len(tmp.Content) == 0 {
			return nil
		}
		tmp = tmp.Content[0]
	}
	if tmp.Kind != yaml.MappingNode {
		return fmt.Errorf("encoded CFF document is not a mapping (kind %d)", tmp.Kind)
	}

	for i := 0; i+1 < len(tmp.Content); i += 2 {
		keyNode := tmp.Content[i]
		valNode := tmp.Content[i+1]
		canvas.SetNode(keyNode.Value, valNode)
	}
	return nil
}
