// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
//
// SPDX-License-Identifier: MIT

package cff

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"

	"kiota.ch/projectfile/core/v2/pkg/rawdoc"
)

// Write serialises doc to CITATION.cff under dir.
//
//   - If doc.Rest is set (Read populated it, or Clone carried it across), the
//     typed fields are painted back onto the raw node tree — comments, key
//     order, and unknown keys all survive.
//   - If doc.Rest is nil (fresh document being created), a new mapping is
//     built from the typed view with a default header comment. There is
//     intentionally no on-disk fallback: the in-memory document must be
//     self-sufficient.
func Write(dir string, doc *Document) error {
	path := FullPath(dir)

	canvas := doc.Rest
	if canvas == nil {
		canvas = rawdoc.NewYAMLNode()
	}

	// Marshal the body with a BLANK head comment. yaml.v3 parks the document
	// head comment on the first mapping key's HeadComment on re-read, not on
	// root.HeadComment, so a comment we leave on the canvas is re-absorbed and
	// re-emitted on the next run — stacking one copy per Write. Clearing root
	// is not enough (the key comment survives), so we also strip every leading
	// comment from the marshalled bytes below and prepend the exact header we
	// want. That makes the head comment a pure Write-time output, never an
	// inherited canvas value, which is what stops the accumulation.
	canvas.SetHeadComment("")

	// Prune legacy non-spec top-level keys we no longer emit. CFF 1.2.0
	// only defines `authors` and `contact` for people; older pf-cli output
	// included `maintainers` / `contributors` and any on-disk file from
	// that era still carries them. Without an explicit Delete, the painter
	// (which only writes typed keys) would leave them stranded and the
	// validator would reject the result.
	canvas.Delete("maintainers")
	canvas.Delete("contributors")

	if err := paintTypedFieldsOntoCanvas(doc, canvas); err != nil {
		return fmt.Errorf("paint CFF document onto canvas: %w", err)
	}

	data, err := canvas.Marshal()
	if err != nil {
		return fmt.Errorf("marshal CFF: %w", err)
	}
	// Drop every leading comment the canvas carried over (root was cleared, but
	// yaml.v3 re-parks a head comment on the first mapping key), then prepend
	// the exact head comment we want. The header is now a Write-time constant,
	// never an inherited value, so no round-trip can stack it.
	body := stripLeadingComments(data)
	header := headCommentFor(doc)
	data = prependHeadComment([]byte(header), body)
	// Runtime gate: validate against the embedded CFF 1.2.0 schema before
	// touching disk. The mapper's shape-aware copy is the producer-side fix
	// for the person/entity bug class; this is the belt-and-braces check
	// that catches drift in any future caller — and any human-edited canvas
	// that has slipped through Read. Validate on the typed YAML body
	// (REUSE header is not YAML content).
	if err := Validate(data); err != nil {
		return fmt.Errorf("CITATION.cff schema validation: %w", err)
	}
	if len(data) > 0 && data[len(data)-1] != '\n' {
		data = append(data, '\n')
	}
	return os.WriteFile(path, data, 0o644) // #nosec G306 -- metadata file, not a secret
}

// WriteMerge is the legacy name retained for callers that haven't moved to
// Write yet. It is identical behaviour.
func WriteMerge(dir string, doc *Document) error {
	return Write(dir, doc)
}

// headCommentFor composes the YAML comment lines that form the document head.
// Each returned line already carries its `#` leader so prependHeadComment can
// emit them verbatim. The REUSE block is optional because non-sync callers
// (host tooling, tests) set ReuseHeader to "" and get only the pf-cli banner.
func headCommentFor(doc *Document) string {
	if doc.ReuseHeader == "" {
		return bannerCommentLines
	}
	// REUSEHeader ends with a blank separator line; the banner follows it.
	return strings.TrimSuffix(doc.ReuseHeader, "\n") + "\n" + bannerCommentLines
}

// bannerCommentLines is the pf-cli pedigree banner as ready-to-emit YAML
// comment lines (each prefixed with `#`).
const bannerCommentLines = "#  CITATION.cff generated by projectfile/cli\n" +
	"#  https://citation-file-format.github.io/"

// stripLeadingComments removes every comment and blank line between the YAML
// document marker `---` and the first data key. It produces a comment-free
// body so prependHeadComment can stamp the single authoritative header. Blank
// lines left by the removed comments are dropped so no stray separators remain.
func stripLeadingComments(data []byte) []byte {
	lines := strings.Split(string(data), "\n")
	out := make([]string, 0, len(lines))
	consumedHead := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if !consumedHead {
			if trimmed == "---" {
				out = append(out, line)
				continue
			}
			// Still in the leading comment/blank region before the first key.
			if trimmed == "" || strings.HasPrefix(trimmed, "#") {
				continue
			}
			// First data line: keep it and stop consuming.
			consumedHead = true
		}
		out = append(out, line)
	}
	return []byte(strings.Join(out, "\n"))
}

// prependHeadComment inserts the comment block `head` right after the YAML
// document marker `---`. The head lines are emitted verbatim (they already
// carry their `#` leaders); a blank separator line follows before the body.
// When head is empty the body is returned unchanged.
func prependHeadComment(head, body []byte) []byte {
	if len(head) == 0 {
		return body
	}
	lines := strings.Split(string(body), "\n")
	marker := -1
	for i, l := range lines {
		if strings.TrimSpace(l) == "---" {
			marker = i
			break
		}
	}
	if marker < 0 {
		return body
	}
	block := []string{}
	for _, l := range strings.Split(string(head), "\n") {
		if l == "" {
			continue
		}
		block = append(block, l)
	}
	block = append(block, "")
	out := append([]string{}, lines[:marker+1]...)
	out = append(out, block...)
	out = append(out, lines[marker+1:]...)
	return []byte(strings.Join(out, "\n"))
}

// paintTypedFieldsOntoCanvas marshals the typed doc to a yaml.Node and copies
// each top-level key into the canvas. Unknown keys on the canvas (anything
// the typed view does not understand) are left alone.
func paintTypedFieldsOntoCanvas(doc *Document, canvas *rawdoc.YAMLNode) error {
	// Marshal the typed view into an intermediate node tree to obtain stable
	// node values per key.
	tmp := &yaml.Node{}
	if err := tmp.Encode(doc); err != nil {
		return err
	}
	if tmp.Kind == yaml.DocumentNode {
		if len(tmp.Content) == 0 {
			return nil
		}
		tmp = tmp.Content[0]
	}
	if tmp.Kind != yaml.MappingNode {
		return fmt.Errorf("encoded CFF document is not a mapping (kind %d)", tmp.Kind)
	}

	for i := 0; i+1 < len(tmp.Content); i += 2 {
		keyNode := tmp.Content[i]
		valNode := tmp.Content[i+1]
		canvas.SetNode(keyNode.Value, valNode)
	}
	return nil
}
