// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
//
// SPDX-License-Identifier: MIT

package cff

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// minimalValidDoc returns a CFF document the embedded 1.2.0 schema accepts, so
// the Write validation gate does not reject the test fixture.
func minimalValidDoc() *Document {
	d := New()
	d.Title = "Projectfile Bridges"
	d.Abstract = "Test abstract"
	d.Authors = []PersonEntity{{FamilyNames: "Búho", GivenNames: "Damián"}}
	d.License = "MIT"
	return d
}

// REUSE-IgnoreStart — the literal SPDX strings below are test fixtures, not
// licensing declarations; REUSE must not parse them as licence expressions.
const testReuseHeader = "# SPDX-FileCopyrightText: 2026 Test Holder\n" +
	"# SPDX-License-Identifier: MIT\n\n"

// REUSE-IgnoreEnd

// TestWrite_RoundTripDoesNotAccumulateSPDX pins the regression: before the
// fix, each Read+Write cycle stacked one extra REUSE block because yaml.v3
// parks the document head comment on the first mapping key's HeadComment on
// re-read, so root.HeadComment (which SetHeadComment resets) and the inherited
// key comment both emitted on the next marshal. Three cycles must yield
// exactly one copyright line and one banner line.
func TestWrite_RoundTripDoesNotAccumulateSPDX(t *testing.T) {
	dir := t.TempDir()

	doc := minimalValidDoc()
	doc.ReuseHeader = testReuseHeader

	for run := 1; run <= 3; run++ {
		if Exists(dir) {
			rd, err := Read(dir)
			if err != nil {
				t.Fatalf("run %d read: %v", run, err)
			}
			rd.ReuseHeader = doc.ReuseHeader
			doc = rd
		}
		if err := Write(dir, doc); err != nil {
			t.Fatalf("run %d write: %v", run, err)
		}
	}

	got := readCFF(t, dir)
	if count := strings.Count(got, "SPDX-FileCopyrightText"); count != 1 {
		t.Errorf("expected exactly 1 copyright line after 3 cycles, got %d\n%s", count, got)
	}
	if count := strings.Count(got, "SPDX-License-Identifier"); count != 1 {
		t.Errorf("expected exactly 1 license line after 3 cycles, got %d\n%s", count, got)
	}
	// The banner must still be present exactly once.
	if count := strings.Count(got, "CITATION.cff generated by projectfile/cli"); count != 1 {
		t.Errorf("expected exactly 1 banner line, got %d\n%s", count, got)
	}
}

// TestWrite_NoReuseHeaderKeepsBannerOnly verifies a non-sync caller (empty
// ReuseHeader) still writes the pf-cli banner and emits zero SPDX lines, so the
// head-comment composition does not regress the header-free path.
func TestWrite_NoReuseHeaderKeepsBannerOnly(t *testing.T) {
	dir := t.TempDir()
	doc := minimalValidDoc() // ReuseHeader stays ""

	if err := Write(dir, doc); err != nil {
		t.Fatalf("write: %v", err)
	}
	got := readCFF(t, dir)
	if strings.Contains(got, "SPDX-") {
		t.Errorf("expected no SPDX lines without ReuseHeader, got:\n%s", got)
	}
	if !strings.Contains(got, "CITATION.cff generated by projectfile/cli") {
		t.Errorf("banner missing:\n%s", got)
	}
}

func readCFF(t *testing.T, dir string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(dir, CFFPath))
	if err != nil {
		t.Fatalf("read CITATION.cff: %v", err)
	}
	return string(b)
}
