// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
//
// SPDX-License-Identifier: MIT

// Command pf-bridge-scan is generated by .scripts/gen-bridge-cmds.sh.
package main

import (
	"projectfile.org/projectfile/bridge/internal/scancmd"
)

func main() { scancmd.Main("pf-bridge-scan") }
