// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
//
// SPDX-License-Identifier: MIT

package codeowners

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

// header is a two-line REUSE block in the shape core.REUSEHeader emits, with
// the tags assembled from fragments so the REUSE linter does not read this
// fixture as the file’s own licence declaration.
const (
	tagCopyright = spdxTagPrefix + "FileCopyright" + "Text: 2026 Example"
	tagLicense   = spdxTagPrefix + "License-" + "Identifier: MIT"
	header       = "# " + tagCopyright + "\n#\n# " + tagLicense + "\n\n"
)

// readBack parses generated bytes the way Read does, so a write→read→write
// round trip can be asserted without touching disk.
func readBack(data []byte) *Document {
	doc := &Document{}
	for _, raw := range strings.Split(strings.TrimSuffix(string(data), "\n"), "\n") {
		doc.Lines = append(doc.Lines, parseLine(raw))
	}
	return doc
}

// TestBytesDoesNotStackTheHeader pins the round-trip invariant: Read keeps the
// header it found as ordinary comments, so a second write must replace it, not
// prepend another copy.
func TestBytesDoesNotStackTheHeader(t *testing.T) {
	t.Parallel()

	first := Bytes(&Document{
		ReuseHeader: header,
		Lines:       []Line{{Kind: KindEntry, Pattern: "*", Owners: []string{"dev@example.org"}}},
	})

	reread := readBack(first)
	reread.ReuseHeader = header
	second := Bytes(reread)

	assert.Equal(t, string(first), string(second), "a re-write must be byte-stable")
	assert.Equal(t, 1, strings.Count(string(second), tagLicense),
		"the licence tag must appear exactly once")
}

// TestBytesKeepsCommentsBelowTheHeader pins the strip boundary: only the
// generated header goes, never a comment a human wrote under it.
func TestBytesKeepsCommentsBelowTheHeader(t *testing.T) {
	t.Parallel()

	doc := readBack(Bytes(&Document{
		ReuseHeader: header,
		Lines: []Line{
			{Kind: KindComment, Text: " infra team owns the deploy scripts"},
			{Kind: KindEntry, Pattern: "/deploy/", Owners: []string{"ops@example.org"}},
		},
	}))
	doc.ReuseHeader = header

	assert.Contains(t, string(Bytes(doc)), "# infra team owns the deploy scripts")
}
