// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
//
// SPDX-License-Identifier: MIT

package shard

import (
	"fmt"
	"os"
	"strings"

	"go.yaml.in/yaml/v3"

	"kiota.ch/projectfile/core/v2/pkg/rawdoc"
)

// Write serialises doc to the shard manifest under dir, preserving unknown keys.
// A hand-written REUSE header always wins untouched: the projectfile is not
// authoritative for the file's rights-holder, so the computed header is only
// gap-filled when the leading block carries no SPDX tags.
func Write(dir string, doc *Document) error {
	path := FullPath(dir)
	canvas := doc.Rest
	if canvas == nil {
		canvas = rawdoc.NewYAMLNode()
	}
	if err := paintTypedFieldsOntoCanvas(doc, canvas); err != nil {
		return fmt.Errorf("paint shard document onto canvas: %w", err)
	}
	data, err := canvas.Marshal()
	if err != nil {
		return fmt.Errorf("marshal shard.yml: %w", err)
	}
	if !hasSPDXTags(data) {
		body := stripLeadingComments(data)
		header := headCommentFor(doc)
		data = prependHeadComment([]byte(header), body)
	}
	if len(data) > 0 && data[len(data)-1] != '\n' {
		data = append(data, '\n')
	}
	return os.WriteFile(path, data, 0o644) // #nosec G306 -- metadata file, not a secret
}

// hasSPDXTags reports whether the rendered bytes already carry SPDX tags.
func hasSPDXTags(data []byte) bool {
	s := string(data)
	return strings.Contains(s, "SPDX-FileCopyrightText") || strings.Contains(s, "SPDX-License-Identifier")
}

// headCommentFor composes the YAML comment lines forming the document head.
func headCommentFor(doc *Document) string {
	if doc.ReuseHeader == "" {
		return bannerCommentLines
	}
	return strings.TrimSuffix(doc.ReuseHeader, "\n") + "#\n" + bannerCommentLines
}

// bannerCommentLines is the pf-bridge pedigree banner as YAML comment lines.
const bannerCommentLines = "# shard.yml generated by pf-bridge\n" +
	"# https://github.com/crystal-lang/shards/blob/master/docs/shard.yml.adoc"

// stripLeadingComments drops comments and blanks before the first data key.
func stripLeadingComments(data []byte) []byte {
	lines := strings.Split(string(data), "\n")
	out := make([]string, 0, len(lines))
	consumedHead := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if !consumedHead {
			if trimmed == "---" {
				out = append(out, line)
				continue
			}
			if trimmed == "" || strings.HasPrefix(trimmed, "#") {
				continue
			}
			consumedHead = true
		}
		out = append(out, line)
	}
	return []byte(strings.Join(out, "\n"))
}

// prependHeadComment inserts the head block right after the YAML marker.
func prependHeadComment(head, body []byte) []byte {
	if len(head) == 0 {
		return body
	}
	lines := strings.Split(string(body), "\n")
	marker := -1
	for i, l := range lines {
		if strings.TrimSpace(l) == "---" {
			marker = i
			break
		}
	}
	if marker < 0 {
		return body
	}
	block := []string{}
	for _, l := range strings.Split(string(head), "\n") {
		if l == "" {
			continue
		}
		block = append(block, l)
	}
	block = append(block, "")
	out := append([]string{}, lines[:marker+1]...)
	out = append(out, block...)
	out = append(out, lines[marker+1:]...)
	return []byte(strings.Join(out, "\n"))
}

// paintTypedFieldsOntoCanvas copies each typed top-level key onto the canvas.
func paintTypedFieldsOntoCanvas(doc *Document, canvas *rawdoc.YAMLNode) error {
	tmp := &yaml.Node{}
	if err := tmp.Encode(doc); err != nil {
		return err
	}
	if tmp.Kind == yaml.DocumentNode {
		if len(tmp.Content) == 0 {
			return nil
		}
		tmp = tmp.Content[0]
	}
	if tmp.Kind != yaml.MappingNode {
		return fmt.Errorf("encoded shard document is not a mapping (kind %d)", tmp.Kind)
	}
	for i := 0; i+1 < len(tmp.Content); i += 2 {
		keyNode := tmp.Content[i]
		valNode := tmp.Content[i+1]
		canvas.SetNode(keyNode.Value, valNode)
	}
	return nil
}
