#!/bin/sh

# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
#
# SPDX-License-Identifier: MIT

set -eu

# =============================================================================
# gen-bridge-cmds.sh — (re)generate the per-bridge binary main packages
# =============================================================================
#
# One binary per bridge (git-style dispatch, Bridge Revolution §5). Each
# cmd/pf-bridge-<pkg>/main.go blank-imports ONLY its own bridge package so that
# binary links only its own code, then calls bridgerun.Main. Every bridge under
# internal/bridge/ (except core) gets a binary; forge/scan/init get theirs from
# their own command packages. Idempotent — safe to re-run after adding a bridge.
# =============================================================================

root="$(cd "$(dirname "$0")/.." && pwd)"
mod="projectfile.org/projectfile/bridge"
cmd_dir="${root}/cmd"

log() { printf '[gen-bridge-cmds] %s\n' "$*" >&2; }

gen_main() {
    # $1 binary suffix   $2 blank-import path (may be empty)   $3 Main() pkg path
    suffix="$1"; import="$2"; mainpkg="$3"
    pkgbase="$(basename "${mainpkg}")"
    dir="${cmd_dir}/pf-bridge-${suffix}"
    mkdir -p "${dir}"
    {
        # REUSE-IgnoreStart — the SPDX tags below are the template written INTO
        # the generated main.go files, not this script's own licence. Wrapping
        # them stops `reuse lint` from parsing the literals as this file's tags.
        printf '// SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>\n'
        printf '//\n// SPDX-License-Identifier: MIT\n\n'
        # REUSE-IgnoreEnd
        printf '// Command pf-bridge-%s is generated by .scripts/gen-bridge-cmds.sh.\n' "${suffix}"
        printf 'package main\n\n'
        printf 'import (\n'
        [ -n "${import}" ] && printf '\t_ "%s"\n\n' "${import}"
        printf '\t"%s"\n' "${mainpkg}"
        printf ')\n\n'
        printf 'func main() { %s.Main("pf-bridge-%s") }\n' "${pkgbase}" "${suffix}"
    } >"${dir}/main.go"
    log "wrote cmd/pf-bridge-${suffix}/main.go"
}

# File bridges: one binary each, blank-importing its own package.
for pkg in "${root}"/internal/bridge/*/; do
    name="$(basename "${pkg}")"
    [ "${name}" = core ] && continue
    gen_main "${name}" "${mod}/internal/bridge/${name}" "${mod}/internal/bridgerun"
done

# Non-bridge tools: their command packages carry their own Main.
gen_main forge "" "${mod}/internal/forgecmd"
gen_main scan  "" "${mod}/internal/scancmd"
gen_main init  "" "${mod}/internal/initcmd"
gen_main cache "" "${mod}/internal/cachecmd"

log "done"
